import { Geist, Geist_Mono, Lekton } from "next/font/google";
import "./globals.css";
import Background from "@/components/background";

const lekton = Lekton({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "portfolio",
  description: "Generated by portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`{lekton.className} relative z-0`}
      >
        <Background />
        {children}
      </body>
    </html>
  );
}
